version: '2'

services:

  # cloudflare configuration
  certbot:
    build: .
    container_name: certbot
    volumes:
      - ~/certificates:/certs
      - ~/certbot/logs:/var/log/letsencrypt
      - ~/certbot/cloudflare.ini:/root/cloudflare.ini:ro
    environment:
      - LOGFILE=/var/log/letsencrypt/certrenewal.log
      - PLUGIN=dns-cloudflare
      - PREFERRED_CHALLENGES=dns-01
      - CUSTOM_ARGS=--no-eff-email --dns-cloudflare-credentials /root/cloudflare.ini
      - RUN_AT_START=true
      - DOMAINS=*.test.example.com
      - EMAIL=info@example.com
      - DEBUG=true
      - STAGING=true